# Spring
spring:
  application:
    name: eureka-server # 应用名称
server:
  port: 9000 #端口

#配置eureka server
eureka:
  instance:
    hostname: localhost   # localhost
  client:
    #当前的eureka服务是单机版的
    register-with-eureka: false #是否将自己注册到注册中心
#    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: false #是否从eureka中获取注册信息
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔


#测试eureka服务是多机版的
#iaed复制模拟两个EurekaServer
#端口9000 , 8000
#两个server需要相互注册
