## 指定Eureka服务地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9099/eureka
#
#zuul:
#  prefix: /api
#
##指定服务的名称
#spring:
#  application:
#    name: zuuldemo
#
#server:
#  port: 80

server:
  port: 10010
spring:
  application:
    name: zuuldemo
zuul:
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka