# Generated by Django 5.0.6 on 2024-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='url',
            field=models.TextField(default='', verbose_name='音乐文件URL'),
        ),
    ]
