// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	Page    int64  `json:"page"`
	Size    int64  `json:"size"`
	Sort    string `json:"sort,optional"`
	Oder    string `json:"order,optional"`
	KeyWord string `json:"keyWord,optional"`
}

type PageData struct {
	Page  int64 `json:"page"`
	Size  int64 `json:"size"`
	Total int64 `json:"total"`
}

type PageListData struct {
	List       interface{} `json:"list"`
	Pagination PageData    `json:"pagination"`
}

type PageResp struct {
	Code int64        `json:"code"`
	Data PageListData `json:"data"`
	Msg  string       `json:"msg"`
}

type Resp struct {
	Code int64       `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}

type CaptchaRequest struct {
	Width  int `form:"width"`
	Height int `form:"height"`
}

type LoginRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
}

type MenuData struct {
	Id         int64  `json:"id"`         // ID
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
	ParentId   int64  `json:"parentId"`   // 父菜单ID
	Name       string `json:"name"`       // 菜单名称
	Router     string `json:"router"`     // 菜单地址
	Perms      string `json:"perms"`      // 权限标识
	Type       int64  `json:"type"`       // 类型 0：目录 1：菜单 2：按钮
	Icon       string `json:"icon"`       // 图标
	OrderNum   int64  `json:"orderNum"`   // 排序
	ViewPath   string `json:"viewPath"`   // 视图地址
	KeepAlive  bool   `json:"keepAlive"`  // 路由缓存
	IsShow     bool   `json:"isShow"`     // 父菜单名称
}

type MenuInfoReq struct {
	Id int64 `form:"id"`
}

type MenuAddReq struct {
	ParentId  int64  `json:"parentId,optional"`            // 父菜单ID
	Name      string `json:"name"`                         // 菜单名称
	Router    string `json:"router,optional"`              // 菜单地址
	Perms     string `json:"perms,optional"`               // 权限标识
	Type      int64  `json:"type"`                         // 类型 0：目录 1：菜单 2：按钮
	Icon      string `json:"icon,optional"`                // 图标
	OrderNum  int64  `json:"orderNum,optional"`            // 排序
	ViewPath  string `json:"viewPath,optional"`            // 视图地址
	KeepAlive bool   `json:"keepAlive,optional"`           // 路由缓存
	IsShow    bool   `json:"isShow,default=true,optional"` // 父菜单名称
}

type MenuUpdateReq struct {
	Id        int64  `json:"id"`                               // ID
	ParentId  int64  `json:"parentId,optional"`                // 父菜单ID
	Name      string `json:"name"`                             // 菜单名称
	Router    string `json:"router,optional"`                  // 菜单地址
	Perms     string `json:"perms,optional"`                   // 权限标识
	Type      int64  `json:"type"`                             // 类型 0：目录 1：菜单 2：按钮
	Icon      string `json:"icon,optional"`                    // 图标
	OrderNum  int64  `json:"orderNum,optional"`                // 排序
	ViewPath  string `json:"viewPath,optional"`                // 视图地址
	KeepAlive bool   `json:"keepAlive,default=false,optional"` // 路由缓存
	IsShow    bool   `json:"isShow,default=true,optional"`     // 父菜单名称
}

type MenuDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type UserListReq struct {
	Page    int64   `json:"page"`
	Size    int64   `json:"size"`
	Sort    string  `json:"sort,optional"`
	Oder    string  `json:"order,optional"`
	KeyWord string  `json:"keyWord,optional"`
	DeptId  []int64 `json:"departmentIds,optional"`
}

type UserInfoData struct {
	Id           int64   `json:"id"`
	CreateTime   string  `json:"createTime"`
	UpdateTime   string  `json:"updateTime"`
	DepartmentId int64   `json:"departmentId"`
	Name         string  `json:"name"`
	NickName     string  `json:"nickName"`
	HeadImg      string  `json:"headImg,optional"`
	Phone        string  `json:"phone,optional"`
	Email        string  `json:"email,optional"`
	Status       bool    `json:"status,optional"`
	Remark       string  `json:"remark,optional"`
	RoleIdList   []int64 `json:"roleIdList"`
}

type UserListData struct {
	Id             int64  `json:"id"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
	DepartmentId   int64  `json:"departmentId"`
	Name           string `json:"name"`
	Username       string `json:"username"`
	NickName       string `json:"nickName"`
	HeadImg        string `json:"headImg"`
	Phone          string `json:"phone"`
	Email          string `json:"email"`
	Status         bool   `json:"status"`
	Remark         string `json:"remark"`
	RoleName       string `json:"roleName"`
	DepartmentName string `json:"departmentName"`
}

type UserAddReq struct {
	DepartmentId int64   `json:"departmentId"`
	Name         string  `json:"name"`
	Username     string  `json:"username"`
	NickName     string  `json:"nickName"`
	HeadImg      string  `json:"headImg,optional"`
	Phone        string  `json:"phone,optional"`
	Email        string  `json:"email,optional"`
	Status       bool    `json:"status"`
	Remark       string  `json:"remark,optional"`
	RoleIdList   []int64 `json:"roleIdList"`
}

type UserInfoReq struct {
	Id int64 `form:"id"`
}

type UserUpdateReq struct {
	Id           int64   `json:"id"`
	CreateTime   string  `json:"createTime"`
	UpdateTime   string  `json:"updateTime"`
	DepartmentId int64   `json:"departmentId"`
	Name         string  `json:"name"`
	NickName     string  `json:"nickName"`
	HeadImg      string  `json:"headImg,optional"`
	Phone        string  `json:"phone,optional"`
	Email        string  `json:"email,optional"`
	Status       bool    `json:"status,optional"`
	Remark       string  `json:"remark,optional"`
	RoleIdList   []int64 `json:"roleIdList"`
}

type UserMoveReq struct {
	DepartmentId int64   `json:"departmentId"`
	UserIds      []int64 `json:"userIds"`
}

type DeptData struct {
	Id         int64  `json:"id"`         // ID
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
	Name       string `json:"name"`       // 部门名称
	ParentId   int64  `json:"parentId"`   // 上级部门ID
	OrderNum   int64  `json:"orderNum"`   // 排序
	ParentName string `json:"parentName"` // 上级部门名称
}

type DeptAddReq struct {
	Name     string `json:"name"`     // 部门名称
	ParentId int64  `json:"parentId"` // 上级部门ID
	OrderNum int64  `json:"orderNum"` // 排序
}

type DeptDeleteReq struct {
	DeleteUser bool    `json:"deleteUser"` // 是否删除会员
	Ids        []int64 `json:"ids"`        // 删除数组
}

type DeptOrderData struct {
	Id       int64 `json:"id"`
	OrderNum int64 `json:"orderNum"`
	ParentId int64 `json:"parentId"`
}

type DeptOrderReq struct {
	Data []DeptOrderData `json:"data"`
}

type RoleListPageReq struct {
	Page    int64  `json:"page"`
	Size    int64  `json:"size"`
	Sort    string `json:"sort,optional"`
	Oder    string `json:"order,optional"`
	KeyWord string `json:"keyWord,optional"`
}

type RoleData struct {
	Id               int64   `json:"id"`
	CreateTime       string  `json:"createTime"`
	UpdateTime       string  `json:"updateTime"`
	Name             string  `json:"name"`
	Label            string  `json:"label"`
	Remark           string  `json:"remark"`
	Relevance        int64   `json:"relevance"`
	MenuIdList       []int64 `json:"menuIdList"`
	DepartmentIdList []int64 `json:"departmentIdList"`
}

type RoleAddReq struct {
	Name             string  `json:"name"`
	Label            string  `json:"label"`
	Remark           string  `json:"remark,optional"`
	Relevance        int64   `json:"relevance"`
	MenuIdList       []int64 `json:"menuIdList"`
	DepartmentIdList []int64 `json:"departmentIdList"`
}

type RoleDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type RoleInfoReq struct {
	Id int64 `form:"id"`
}

type RoleUpdateReq struct {
	Id               int64   `json:"id"`
	Name             string  `json:"name"`
	Label            string  `json:"label"`
	Remark           string  `json:"remark,optional"`
	Relevance        int64   `json:"relevance"`
	MenuIdList       []int64 `json:"menuIdList"`
	DepartmentIdList []int64 `json:"departmentIdList"`
}

type ConfigInfoReq struct {
	Type int64 `form:"type"`
}

type ConfigUpdateData struct {
	Appid          string `json:"appId"`
	AppSecret      string `json:"appSecret"`
	EncodingAESKey string `json:"EncodingAESKey,optional"`
	Token          string `json:"Token,optional"`
}

type ConfigUpdateReq struct {
	Data ConfigUpdateData `json:"data"`
	Type int64            `json:"type"`
}

type AutoReply struct {
	Active  string         `json:"active"`
	Media   []MaterialData `json:"media,optional"`
	Mediaid int64          `json:"media_id,optional"`
	Text    string         `json:"text,optional"`
	Url     string         `json:"url,optional"`
}

type Attention struct {
	Active  string         `json:"active"`
	Media   []MaterialData `json:"media,optional"`
	Mediaid int64          `json:"media_id,optional"`
	Text    string         `json:"text,optional"`
	Url     string         `json:"url,optional"`
}

type ConfigReplyUpdateData struct {
	AutoReply AutoReply `json:"autoReply"`
	Attention Attention `json:"attention"`
}

type ConfigReplyUpdateReq struct {
	Type int64                 `json:"type"`
	Data ConfigReplyUpdateData `json:"data"`
}

type MaterialData struct {
	Url              string `json:"url,optional"`                // 地址
	Type             string `json:"type,optional"`               // 类型
	Title            string `json:"title,optional"`              // 标题
	Author           string `json:"author,optional"`             // 作者
	Cover            string `json:"cover,optional"`              // 图片封面
	Summary          string `json:"summary,optional"`            // 摘要
	Content          string `json:"content"`                     // 正文
	ContentSourceUrl string `json:"content_source_url,optional"` // 原文URL
	Sort             int64  `json:"sort,optional"`               // 排序
	Hits             int64  `json:"hits,optional"`               // 阅读次数
	MediaKey         int64  `json:"media_key,optional"`
}

type MaterialAddReq struct {
	Title string         `json:"title"`
	Thumb string         `json:"thumb"`
	Data  []MaterialData `json:"data"`
}

type MaterialItemListReq struct {
	Id int64 `form:"id"`
}

type WechatMenuData struct {
	Type       string            `json:"type"`
	Name       string            `json:"name,optional"`
	URL        string            `json:"url,optional"`
	MediaID    int64             `json:"media_id,optional"`
	MsgType    string            `json:"msgType"`
	AppID      string            `json:"app_id,optional"`
	PagePath   string            `json:"page_path,optional"`
	Text       string            `json:"text,optional"`
	Pic        string            `json:"pic,optional"`
	SubButtons []*WechatMenuData `json:"sub_button,optional"`
}

type WechatMenuAddReq struct {
	Data []WechatMenuData `json:"data"`
}

type AddReplyReq struct {
	Key     string `json:"key"`
	Match   bool   `json:"match"`
	MediaId int64  `json:"mediaId,optional"`
	Name    string `json:"name"`
	Text    string `json:"text,optional"`
	Type    string `json:"type,optional"`
	Url     string `json:"url,optional"`
}

type ReplyInfoReq struct {
	Id int64 `form:"id"`
}

type ReplyInfoData struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Key        string `json:"key"`   // 关键词
	Match      bool   `json:"match"` // 回复类型
	Type       string `json:"type"`
	MediaId    int64  `json:"mediaId"` // 回复媒体内容id
	Text       string `json:"text"`    // 回复文本
	Url        string `json:"url"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type ReplyDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type ItemPageReq struct {
	PageData
	ClassifyId int64 `json:"classifyId,optional"`
}

type ItemPageData struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
	Url        string `json:"url"`
	Type       string `json:"type"`
	ClassifyId int64  `json:"classifyId"`
}

type ItemAddReq struct {
	ClassifyId int64  `json:"classifyId,optional"`
	Type       string `json:"type"`
	Url        string `json:"url"`
}

type UploadReq struct {
	File string `form:"file"`
}

type TypeAddReq struct {
	Name string `json:"name"`
}

type TypeUpdateReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type TypeDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type TypeListData struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
	Name       string `json:"name"`
}
