server:
  port: 6670
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 741106
    url: jdbc:mysql://127.0.0.1:3306/ds-0
    #配置数据源，设置 useInformationSchema 可以获取tables注释信息。
    xa:
      properties:
        useInformationSchema=true: