server:
  tomcat:
    basedir: ./logs/newblog

spring:
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 741106
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
#      host: 43.153.15.174
#      password: 0CVF5Dsh79

