// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleBox: typeof import('./components/Box/articleBox/articleBox.vue')['default']
    ArticleRight: typeof import('./components/Box/rightToolsBox/ArticleRight.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Foot: typeof import('./components/Foot/Foot.vue')['default']
    Index: typeof import('./components/Index/Index.vue')['default']
    Index2: typeof import('./components/Index/Index2.vue')['default']
    IndexArticle: typeof import('./components/Index/IndexArticle.vue')['default']
    'IndexArticle copy': typeof import('./components/Index/IndexArticle copy.vue')['default']
    Loading: typeof import('./components/Loading/Loading.vue')['default']
    Loading2: typeof import('./components/Loading/loading2.vue')['default']
    Login: typeof import('./components/Login/Login.vue')['default']
    MiniMessage: typeof import('./components/Box/rightToolsBox/miniMessage.vue')['default']
    Navigation: typeof import('./components/Navigation/Navigation.vue')['default']
    NavMore: typeof import('./components/Navigation/navMore.vue')['default']
    NavUserInfo: typeof import('./components/Navigation/NavUserInfo.vue')['default']
    RandomArticle: typeof import('./components/Box/rightToolsBox/randomArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArticleBox: typeof import('./components/Box/topArticleBox/TopArticleBox.vue')['default']
  }
}

export {}
