server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://1.2.3.4:3306/xiaofu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: 公众号：程序员小富
    password: ENC(mVTvp4IddqdaYGqPl9lCQbzM3H/b0B6l)

jasypt:
  encryptor:
    password: 35579B7F9C8CB15E
    poolSize: 3