mysql:
  address: 127.0.0.1:3306  #数据库的连接地址
  username: root          #数据库账号
  password: 123456      #数据库密码

alipay:
  sandboxAccount:  #仅用于测试账号，无实际配置用处
  sandboxPassword:  #仅用于测试密码，无实际配置用处

  appId:  #支付宝应用id
  privateKey:  #应用私钥

  cert: #加载证书（没有可不加）
    appPublicCertPath:  #应用公钥证书路径
    alipayRootCertPath:  #支付宝根证书路径
    alipayPublicCertPath:  #支付宝公钥证书路径

  url: #地址
    notifyURL:  #回调地址（支付成功后会发送一个POST消息到该地址）
    returnURL:  #返回地址（支付成功后浏览器将会重定向到该 URL）

aliYunOSS:
  endpoint:   #endpint地域节点
  accessKeyId:   #主账号accessKey
  accessKeySecret:   #主账号key密钥
  profileBucket: starlight-profile  #头像bucket
  OSSClientURL:  #URL地址

redis:
  address: 127.0.0.1:6379  #redis的连接地址

email:
  senderEmail:  #发送者Email
  SMTPServer:  #SMTP服务器
  SMTPPort:  #SMTP服务器端口
  SMTPKey:  #SMTP授权码