// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonAck struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonAck) Reset()         { *m = CommonAck{} }
func (m *CommonAck) String() string { return proto.CompactTextString(m) }
func (*CommonAck) ProtoMessage()    {}
func (*CommonAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CommonAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonAck.Unmarshal(m, b)
}
func (m *CommonAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonAck.Marshal(b, m, deterministic)
}
func (m *CommonAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonAck.Merge(m, src)
}
func (m *CommonAck) XXX_Size() int {
	return xxx_messageInfo_CommonAck.Size(m)
}
func (m *CommonAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonAck.DiscardUnknown(m)
}

var xxx_messageInfo_CommonAck proto.InternalMessageInfo

func (m *CommonAck) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonAck) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignupReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupReq) Reset()         { *m = SignupReq{} }
func (m *SignupReq) String() string { return proto.CompactTextString(m) }
func (*SignupReq) ProtoMessage()    {}
func (*SignupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SignupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReq.Unmarshal(m, b)
}
func (m *SignupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReq.Marshal(b, m, deterministic)
}
func (m *SignupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReq.Merge(m, src)
}
func (m *SignupReq) XXX_Size() int {
	return xxx_messageInfo_SignupReq.Size(m)
}
func (m *SignupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReq proto.InternalMessageInfo

func (m *SignupReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignupReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonAck)(nil), "proto.CommonAck")
	proto.RegisterType((*SignupReq)(nil), "proto.SignupReq")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x96, 0x5c, 0x9c, 0xce, 0xf9,
	0xb9, 0xb9, 0xf9, 0x79, 0x8e, 0xc9, 0xd9, 0x42, 0x42, 0x5c, 0x2c, 0xce, 0xf9, 0x29, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71,
	0x62, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0xe4, 0xcc, 0xc5, 0x19,
	0x9c, 0x99, 0x9e, 0x57, 0x5a, 0x10, 0x94, 0x5a, 0x28, 0x24, 0xc5, 0xc5, 0x11, 0x5a, 0x9c, 0x5a,
	0xe4, 0x97, 0x98, 0x0b, 0xd1, 0xce, 0x19, 0x04, 0xe7, 0x83, 0xe4, 0x02, 0x12, 0x8b, 0x8b, 0xcb,
	0xf3, 0x8b, 0x52, 0xa0, 0x66, 0xc0, 0xf9, 0x46, 0xb6, 0x5c, 0xdc, 0x20, 0x75, 0xc1, 0xa9, 0x45,
	0x65, 0x99, 0xc9, 0xa9, 0x42, 0x7a, 0x5c, 0x6c, 0x10, 0x33, 0x85, 0x04, 0x20, 0xee, 0xd4, 0x83,
	0x5b, 0x21, 0x05, 0x13, 0x81, 0xbb, 0x57, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x64, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x29, 0xa7, 0xa9, 0xd6, 0xda, 0x00, 0x00, 0x00,
}
