###初始化分块文件
POST http://{{host}}/initmultipart
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "FileName": "go1.13.8.linux-amd64.tar.gz",
  "FileHash": "9798f7bb36b780585966e7d0938a7eb954d77f15",
  "FileSize": 120075156
}

###完成分块上传接口
POST http://{{host}}/completeupload
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "UploadId": "A32480FC-5B6A-00B1-835B-E61F2A146D2E"
}

###取消上传分块
POST http://{{host}}/cancelupload
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "UploadId": "7F36C537-CF7F-E28D-A866-E163639E53DD"
}

###获取分块上传整体状态
POST http://{{host}}/multipartuploadstatus
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "UploadId": "C0425C65-1455-35DB-42CA-677EBB91B5A8"
}

###

