###获取文件信息
POST http://{{host}}/file
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}

{"Sha1":"8f49921dc07d96a5080bfb81d32d946468bf0383"}



###编辑文件
POST http://{{host}}/file/edit
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "Sha1": "8f49921dc07d96a5080bfb81d32d946468bf0383",
  "Name": "adfaf1",
  "Ext2":"123123"
}


### 上传文件
POST http://{{host}}/upload
Accept: */*
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=boundary
Token:{{token}}

--boundary
Content-Disposition: form-data; name="file"; filename="input.txt"

// The 'input.txt' file will be uploaded
< ./input.txt

### 文件秒传接口
POST http://{{host}}/fastupload
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Token:{{token}}


{
  "Sha1": "6e99b447950dbad20208cbc61f49ea7b9cd1dd82",
  "Name": "adfaf1",
  "Size": 10
}

###

