logging:
    level:
        org:
            springframework: 'OFF'
        root: 'OFF'
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/*.xml
server:
    port: 9000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 741106
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/lesson3
        username: root
    main:
        banner-mode: 'off'